fixed some bugs with the track counter, additonally now provide a counter to FD2; fixed bug where a while : loop happens after the last offset shift, exits properly now

diff --git a/streaming-apis/spotify/liked-songs b/streaming-apis/spotify/liked-songs
--- a/streaming-apis/spotify/liked-songs
+++ b/streaming-apis/spotify/liked-songs
@@ -15,7 +15,7 @@ R=$(curl -X "GET" "https://api.spotify.com/v1/me/tracks" -H "Accept: application
 } || printf '%s\n' "$R"
 )
 [ "$RETURN" = "FAILED" ] && {
-  echo "AUTHKEY may be invaild, expired, or unset, or other connection errors are occuring..."
+  echo "AUTHKEY may be invaild, expired, or unset, or other connection errors are occuring..." >&2
   exit 1
 }
 length="${RETURN##*?total????}"; length="${length%??}" # ?? should remove closing } and NL
@@ -23,12 +23,12 @@ offset=0
 TRACK_NUM=1
 until [ $offset -ge $length ]; do
   RETURN=$(curl -sL -X "GET" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHKEY" "https://api.spotify.com/v1/me/tracks?limit=50&offset=${offset}")
-  track_num=1; until [ $track_num -ge 50 ]; do
+  n=0; until [ $n -ge 50 ]; do
     RETURN="${RETURN#*?track????\{}" # remove all data before track element
     # handle the album as it appears first
     RETURN="${RETURN#*?\],}" # remove all data within the album artists array
     RETURN="${RETURN#*?id\"????}" # remove all data before the album id
-    ALBUM_ID="${RETURN%%?,*}"
+    ALBUM_ID="${RETURN%%\",*}"
     RETURN="${RETURN#*\],}" # remove all data before and in the images array
     ALBUM_NAME="${RETURN#*?name?????}"; ALBUM_NAME="${ALBUM_NAME%%?,*}"
     # above is all for album data, next is the list of artists for the current track
@@ -37,7 +37,7 @@ until [ $offset -ge $length ]; do
     RETURN="${RETURN#*\},?}"; unset ARTISTS # move to artist block
     until [ "$p" = "]," ]; do
       RETURN="${RETURN#*?name?????}" # remove everything before the name data
-      ARTISTS="${ARTISTS+${ARTISTS}, }${RETURN%%?,*}"; # store name data
+      ARTISTS="${ARTISTS+${ARTISTS}, }${RETURN%%\",*}"; # store name data
       RETURN="${RETURN#*\}?}";
       read -r p << EOF
 $RETURN
@@ -47,15 +47,18 @@ EOF
     done
     unset p
     # until the current line matches the end of an array, do the above
-    RETURN="${RETURN#*?id\"????}"; TRACK_ID="${RETURN%%?,*}" # get track id
+    RETURN="${RETURN#*?id\"????}"; TRACK_ID="${RETURN%%\",*}" # get track id
     RETURN="${RETURN#*?name?????}" # move to track name
-    TRACK_NAME="${RETURN%%?,*}"
+    TRACK_NAME="${RETURN%%\",*}"
     printf 'Track #%s: %s - %s | Album: %s - %s | Artists: %s\n' "$TRACK_NUM" "$TRACK_NAME" "$TRACK_ID" "$ALBUM_NAME" "$ALBUM_ID" "$ARTISTS"
+    #echo "$TRACK_NUM | $TRACK_NAME | $offset"
     RETURN="${RETURN#*\},?\{}" # finish current track
-    : $((track_num+=1))
+    : $((n+=1))
     : $((TRACK_NUM+=1))
+    printf '\r%s/%s/%s' "$TRACK_NUM" "$offset" "$length" >&2
+    [ "$TRACK_NUM" -ge "$length" ] && exit
   done
   # until 50th track
   : $((offset+=50))
+  #[ "$TRACK_NUM" -eq "$length" ] && break
 done
-exit
